apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: uniassist-staging
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: uniassist-staging
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: uniassist-staging
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: uniassist-staging
$patch: delete
