apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-platform-api
  namespace: uniassist-staging
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: workflow-platform-api
          resources:
            requests:
              cpu: "150m"
              memory: "192Mi"
            limits:
              cpu: "400m"
              memory: "384Mi"
