apiVersion: v1
kind: Service
metadata:
  name: adapter-wechat
  namespace: uniassist-staging
  labels:
    app: adapter-wechat
spec:
  selector:
    app: adapter-wechat
  ports:
    - name: http
      port: 8788
      targetPort: 8788
  type: ClusterIP
