apiVersion: v1
kind: Service
metadata:
  name: connector-runtime
  namespace: uniassist-staging
  labels:
    app: connector-runtime
spec:
  selector:
    app: connector-runtime
  ports:
    - name: http
      port: 8895
      targetPort: 8895
