apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: uniassist-staging
  labels:
    app: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      port: 8787
      targetPort: 8787
  type: ClusterIP
