apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - control-console-deployment.yaml
  - control-console-service.yaml
  - workflow-platform-api-deployment.yaml
  - workflow-platform-api-service.yaml
  - workflow-runtime-deployment.yaml
  - workflow-runtime-service.yaml
  - connector-runtime-deployment.yaml
  - connector-runtime-service.yaml
  - trigger-scheduler-deployment.yaml
  - trigger-scheduler-service.yaml
  - worker-deployment.yaml
