apiVersion: v1
kind: Service
metadata:
  name: trigger-scheduler
  namespace: uniassist-staging
  labels:
    app: trigger-scheduler
spec:
  selector:
    app: trigger-scheduler
  ports:
    - name: http
      port: 8793
      targetPort: 8793
