apiVersion: v1
kind: Service
metadata:
  name: workflow-platform-api
  namespace: uniassist-staging
  labels:
    app: workflow-platform-api
spec:
  selector:
    app: workflow-platform-api
  ports:
    - name: http
      port: 8791
      targetPort: 8791
