apiVersion: v1
kind: Service
metadata:
  name: adapter-wechat
  namespace: uniassist-staging
spec:
  type: NodePort
  ports:
    - name: http
      port: 8788
      targetPort: 8788
      nodePort: 30088
