apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: control-console-nodeport-patch.yaml
    target:
      group: ""
      version: v1
      kind: Service
      name: control-console
      namespace: uniassist-staging
  - path: workflow-platform-api-nodeport-patch.yaml
    target:
      group: ""
      version: v1
      kind: Service
      name: workflow-platform-api
      namespace: uniassist-staging
